baseURL = 'https://opticasfausto.com/'
locale = 'es-ES'
defaultContentLanguage = 'es'
title = 'Ópticas Fausto · Centro Óptico y Auditivo en Torre del Mar'
theme = 'f1-theme'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      title = true
      block = true

[params]
  siteName = 'Ópticas Fausto'
  defaultOgImage = '/images/og/opticas-fausto.jpg'
